-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ADMIN', 'WAREHOUSE_STAFF');

-- AlterTable
ALTER TABLE "Users" ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'WAREHOUSE_STAFF',
ALTER COLUMN "password" DROP DEFAULT,
ALTER COLUMN "updatedAt" DROP DEFAULT;
